default:
  http_metas:
    content-type: text/html

  metas:
    title:        Probar Historia
    description:  Probar Historia Usuario
    keywords:     Probar, historia, usuario
    language:     es
    robots:       index, follow

  stylesheets:    [Spinner.css]

  javascripts:    [ PruebaExperto/pruebaHistoria.js, PruebaExperto/Ext.ux.grid.RowExpander.js, Spinner/Spinner.js, Spinner/SpinnerField.js ]

  has_layout:     on
  layout:         layout
