dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        pgsql:dbname=agilhu;host=localhost
      username:   agilhu
      password:   agilhu
      encoding:   utf8
      persistent: true
      pooling:    true
