default:
  http_metas:
    content-type: text/html

  metas:
    title:        Gestion de usuarios
    description:  El administrador del sistema gestiona usuarios
    keywords:     usuarios, gestion
    language:     es
    robots:       index, follow

  stylesheets:    [../extjs/resources/css/ext-all.css,../extjs/resources/css/xtheme-blue.css,main.css]

  javascripts:    [../extjs/adapter/ext/ext-base.js,../extjs/ext-all.js,../extjs/src/locale/ext-lang-es.js,usuario/agGestionUsuario.js,auxiliares/Ext.ux.grid.Search.js,logueo/login.js,auxiliares/funciones.js]

  has_layout:     on
  layout:         layout

